//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KHO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitietnhap
    {
        public string maCTN { get; set; }
        public string maPN { get; set; }
        public string maHH { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<int> donGia { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual HangHoa HangHoa1 { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual PhieuNhap PhieuNhap1 { get; set; }
    }
}
