//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KHO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        public HangHoa()
        {
            this.Chitietnhaps = new HashSet<Chitietnhap>();
            this.Chitietnhaps1 = new HashSet<Chitietnhap>();
            this.Chitietxuats = new HashSet<Chitietxuat>();
            this.Chitietxuats1 = new HashSet<Chitietxuat>();
        }
    
        public string maHH { get; set; }
        public string tenHH { get; set; }
        public string maNCC { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual ICollection<Chitietnhap> Chitietnhaps { get; set; }
        public virtual ICollection<Chitietnhap> Chitietnhaps1 { get; set; }
        public virtual ICollection<Chitietxuat> Chitietxuats { get; set; }
        public virtual ICollection<Chitietxuat> Chitietxuats1 { get; set; }
        public virtual NCC NCC { get; set; }
        public virtual NCC NCC1 { get; set; }
    }
}
