//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KHO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCC
    {
        public NCC()
        {
            this.HangHoas = new HashSet<HangHoa>();
            this.HangHoas1 = new HashSet<HangHoa>();
        }
    
        public string maNCC { get; set; }
        public string tenNCC { get; set; }
        public string diaChi { get; set; }
        public string SDT { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<HangHoa> HangHoas { get; set; }
        public virtual ICollection<HangHoa> HangHoas1 { get; set; }
    }
}
