//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KHO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public PhieuNhap()
        {
            this.Chitietnhaps = new HashSet<Chitietnhap>();
            this.Chitietnhaps1 = new HashSet<Chitietnhap>();
        }
    
        public string maPN { get; set; }
        public Nullable<System.DateTime> ngayNhap { get; set; }
        public Nullable<int> tongTien { get; set; }
    
        public virtual ICollection<Chitietnhap> Chitietnhaps { get; set; }
        public virtual ICollection<Chitietnhap> Chitietnhaps1 { get; set; }
    }
}
