//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KHO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuat
    {
        public PhieuXuat()
        {
            this.Chitietxuats = new HashSet<Chitietxuat>();
            this.Chitietxuats1 = new HashSet<Chitietxuat>();
        }
    
        public string maPX { get; set; }
        public Nullable<System.DateTime> ngayXuat { get; set; }
        public Nullable<int> tongTien { get; set; }
    
        public virtual ICollection<Chitietxuat> Chitietxuats { get; set; }
        public virtual ICollection<Chitietxuat> Chitietxuats1 { get; set; }
    }
}
